# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 24206b58c490814130345f0d3e8a2fde44161df90f7485e2cc315cff107a754d74e13d5f1c436fcd5c97c77091069914ede9b0b99349c2f155bae4e168091501

test:
  secret_key_base: 057f0b152f38e721aeb673f5d2ba1bdca6f9a8e00456f5b8a87f80af8e0747a5b80788678fd2867e3322ab2e39d63e4cb7ae2931e4e0e05d92b1a8bc6053184b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
